import type { NextPage } from "next";
import { signOut } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";

const Index: NextPage = () => {
  return (
    <div>
      <Head>
        <title>LinkedIn Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={() => signOut()}>Sign Out</button>
      LinkedIn Clone
    </div>
  );
};

export default Index;
